name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'mkdocs/**'
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'mkdocs/**'
      - 'src/**'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build API documentation with Doxygen
        run: |
          cd mkdocs
          mkdir -p docs/api
          doxygen Doxyfile

      - name: Build with MkDocs
        run: |
          cd mkdocs
          mkdocs build --clean

      - name: Copy CNAME file
        run: |
          cp mkdocs/CNAME mkdocs/site/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./mkdocs/site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
