name: "Release Docs"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'mkdocs/**'
      - 'src/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Build API documentation with Doxygen
        run: |
          cd mkdocs
          mkdir -p docs/api
          doxygen Doxyfile
          echo "Doxygen output created in docs/api/"

      - name: Build docs
        run: |
          cd mkdocs
          mkdocs build --clean
          echo "MkDocs site built in site/"

      - name: Copy
        working-directory: ./mkdocs
        run: |
          echo "Copying site contents to /tmp/site"
          cp -r ./site/* /tmp/site/

      - name: Push changes to gh-pages branch
        run: |
          git checkout --orphan gh-pages-tmp
          git rm --quiet -rf .
          cp -r /tmp/site/* .
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          echo "cpp.iceberg.apache.org" > CNAME
          git add --all
          git commit -m 'Publish C++ docs'
          git push -f origin gh-pages-tmp:gh-pages || true
