name: "Release Docs"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'mkdocs/**'
      - 'src/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Build API documentation with Doxygen
        run: |
          cd mkdocs
          mkdir -p docs/api
          doxygen Doxyfile
          echo "Doxygen output created in docs/api/"

      - name: Build docs
        run: |
          cd mkdocs
          mkdocs build --clean
          echo "MkDocs site built in site/"

      - name: Copy
        working-directory: ./mkdocs
        run: |
          echo "Copying site contents to /tmp/site"
          mv ./site /tmp/site/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mkdocs/site
          publish_branch: gh-pages
